### ISSUE TITLE
Dependencies not met

### ISSUE THREAD

**Issue by stormsh** [Xycl/plugin.video.amazon_prime_de#1]
Hi, I´m using Kodi 14.0 trying to install Amazon prime instant video addon, but either I get "Dependencies not met - Please contact addon developer" or if I try the master repository it says "Addon does not have the correct structure".

Windows 7 64bit

**Comment by Xycl** [comment]
I don't know what you mean with "master" repo, but:
1) Install AddonScriptorDE's testing repository 
http://code.google.com/p/addonscriptorde-beta-repo/downloads/detail?name=repository.addonscriptorde-beta.zip
It contains add-on Chrome Launcher. The reason you got dependencies not met.
2) Then install my repo
https://github.com/Xycl/repository.xycl.addons/raw/master/repository.xycl.addons/repository.xycl.addons-1.2.1.zip
