### ISSUE TITLE
Chrome not found

### ISSUE THREAD

**Issue by robsdedude** [Xycl/plugin.video.amazon_prime_de#2]
Hi

I'm running kodi on my Raspberry Pi (recalbox). When I try to run Chrome launcher I get the error message "Chrome not found". I assume this is, because there is no chrome installed on the system.

If so: Please add the fact that a chrome installation is needed to the plugin description so that people like don't have to download and launch the plugin first to then notice that it's not working for them.

**Comment by Xycl** [comment]
Will be done
